#Network Settings
domain: ".kunjbr.hom"

# Your Wi-Fi SSID and password
wifi_ssid: "Kunj@BinaRaj"
wifi_password: "keh1n1x@19#$"

engineer_ssid: "Engineer"
engineer_password: "keh1n1x@19#$"

iot_ssid: "IOT"
iot_password: "a1b2c3d4e5"

not_ssid: "NOT"
not_password: "a1b2c3d4e5"


#OTA Update
ota_password: "ota@252999"
fallback_password: "fallback@321"

#API password
api_password: "api@252999"

#WEBSERVER
PORT: 88
web_password: "webserver@252999"

#encryption Keys for the devices
jnp_bedroom_enc_key: "y5mdHYbjp3g2aFyNjnkGHN42oRC2K8ItAY/vPkaO1GQ="
jnp_guestroom_enc_key: "Asn26VImTYcwV54OD3p/i0XZJ4k9ERTCOGPrjKzn+ic="

#devices ip addresses
jnp_bedroom_address: "10.20.10.28"
jnp_guestroom_address: "10.20.10.21"
